CREATE TABLE CUSTOMER (
	AccountID	INT,
	Fname		VARCHAR(25) NOT NULL,
	Lname		VARCHAR(25) NOT NULL,
	UserName	VARCHAR(25) NOT NULL,
	Password	VARCHAR(25) NOT NULL,
	Phone		CHAR(10),
	Email		VARCHAR(40),
	PRIMARY KEY	(AccountID)
);
CREATE TABLE ADMIN (
	AccountID	INT,
	Fname		VARCHAR(25) NOT NULL,
	Lname		VARCHAR(25) NOT NULL,
	UserName	VARCHAR(25) NOT NULL,
	Password	VARCHAR(25) NOT NULL,
	Phone		CHAR(10),
	Email		VARCHAR(40),
	PRIMARY KEY (AccountID)
);
CREATE TABLE PRODUCT (
	ProductID	INT,
	Name		VARCHAR(50) NOT NULL,
	Price		DECIMAL(10, 2) NOT NULL,
	Num	        INT NOT NULL,
	Description	VARCHAR(200),
	Image		VARCHAR(50),
	PRIMARY KEY (ProductID)
);

CREATE TABLE ORDER (
	OrderID		INT,
	AccountID	INT NOT NULL,
	PurchaseDate	DATE NOT NULL,
	TotalPrice	DECIMAL(10, 2) NOT NULL,
	Comments	VARCHAR(200),
	PRIMARY KEY (OrderID),
	FOREIGN KEY (AccountID) REFERENCES CUSTOMER(AccountID) ON DELETE CASCADE
);

CREATE TABLE ORDER_DETAIL (
	OrderID		INT,
	ProductID	INT,
	Name		VARCHAR(50) NOT NULL,
	PurchasedPrice		DECIMAL(10, 2) NOT NULL,
	Num 	    INT NOT NULL,
	PRIMARY KEY (OrderID, ProductID),
	FOREIGN KEY (OrderID) REFERENCES ORDER(OrderID) ON DELETE CASCADE
);

CREATE TABLE CART (
	AccountID	INT NOT NULL,
	TotalPrice	DECIMAL(10, 2) NOT NULL,
	PRIMARY KEY (AccountID),
	FOREIGN KEY (AccountID) REFERENCES CUSTOMER(AccountID) ON DELETE CASCADE
);
CREATE TABLE CART_OWN_PRODUCT (
	AccountID	INT,
	ProductID	INT,
	Num		INT NOT NULL,
	PRIMARY KEY (AccountID, ProductID),
	FOREIGN KEY (AccountID) REFERENCES CUSTOMER(AccountID) ON DELETE CASCADE,
	FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID) ON DELETE CASCADE
);

CREATE TABLE WISHLIST (
	AccountID	INT NOT NULL,
	PRIMARY KEY (AccountID),
	FOREIGN KEY (AccountID) REFERENCES CUSTOMER(AccountID) ON DELETE CASCADE
);
CREATE TABLE WISHLIST_OWN_PRODUCT (
	AccountID	INT,
	ProductID	INT,
	PRIMARY KEY (AccountID, ProductID),
	FOREIGN KEY (AccountID) REFERENCES CUSTOMER(AccountID) ON DELETE CASCADE,
	FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID) ON DELETE CASCADE
);